### ISSUE TITLE
Wer ist AndTheFortyThiefes?!

### ISSUE THREAD

**Issue by Setahero** [LeonardK/curly-rotary-phone#1]
Kann den mal jemand rausschmeißen?!

**Comment by LeonardK** [comment]
Wahrscheinlich der Github-Account des Verfassungsschutzes..? Ich würde ja an deren Stelle schon mal ein Auge auf so ein brisantes Projekt werfen. Irgendwo muss es Antworten auf diese ganzen Fragen geben. Was ist ein curly phone? Warum so viel Geheimhaltung? Wer ist Setahero? In welcher Verbindung steht dieses Projekt zu den Themen der berüchtigten #HappyHölliween und was hat das Ganze eigentlich mit #IS16/17 zu tun????

**Comment by Setahero** [comment]
Und warum gibt es einen Account "Andrey" und wie ist dieser mysteriöse Mensch darin verwickelt?!

**Comment by LeonardK** [comment]
Ich werde dem auf den Grund gehen...
