### ISSUE TITLE
Content: Tabelle

### ISSUE THREAD

**Issue by LeonardK** [LeonardK/curly-rotary-phone#13]
Tabellenansicht mit:
- Filterleiste (Show/Hide: birth rate | cellphones | ...) _über und unter_ der Tabellle
- Spaltenüberschriften, als "thead" implementiert! (ID | Country | ...)
- Datenzeilen, in "tbody"
- Sortier-Buttons bei Spaltenüberschrift "Country"

**Comment by Setahero** [comment]
Too much workload 
Such Paylod

**Comment by LeonardK** [comment]
Much slow progress Wow Such lazy worker

**Comment by Setahero** [comment]
Hey! Ich lese hier während der Vorlesung CSS Artikel durch du Doge!
