### ISSUE TITLE
Beschissener Screenshot

### ISSUE THREAD

**Issue by Setahero** [LeonardK/curly-rotary-phone#20]
Für Teilaufgabe 2 gibt noch ne dirty Implementierung der formatierung des Arrays in xml, da die csv scheinabr nciht die selbe ist wie im screenshot. Habs im Moment durch foreach gelöst, auf Eleganz wurde aber hart "gedoget". Fällt dir was ein wie man das hübscher machen könnte?

**Comment by LeonardK** [comment]
MIGHTY TRIM DOGE HAS SPOKEN
