### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by LeonardK** [LeonardK/curly-rotary-phone#3]
Logo & Navigation:
- Sticky navigation
- Gradient Hintergrund
- Logo mit Hover Effekt & Klickbar (Link auf Startseite)
- Menübuttons mit Hover Effekt (Transition zu dunkelgrau, ohne Gradient)
- Menübuttons unbedingt als "li" (unordered list) implementieren!

**Comment by Setahero** [comment]
sticky navigation ist duch -webkit-sticky nicht von allen Browsern unterstützt. Gibt auch eine js Lösung, die ich mal versuchen werde reinzubringen
