### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by LeonardK** [LeonardK/curly-rotary-phone#5]
Footer unter einem grünen Strich mit folgenden Informationen:
rechts: Copyright, Kursbeschreibung
links: Team und Teamnr.

**Comment by Setahero** [comment]
Das scheint noch jemand eine Links/Rechts Schwäche zu haben ;)

**Comment by Setahero** [comment]
Eigentlich fertig. Aber ich bekomme die erste Zeile des Textes rechts nicht komplett an die rechte seite geklebt. Help!
